import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
// import WalletButton from "./components/WalletButton";

import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Donation Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {/* <header
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            right: 0,
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            padding: "20px 40px",
            backgroundColor: "#f8f9fa",
            borderBottom: "1px solid #e9ecef",
            boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
            zIndex: 50,
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "20px" }}>
            <Link href="/" className="home-link">
              <h1 style={{ margin: 0, fontSize: "1.5rem", color: "#333" }}>
                Donation Solution
              </h1>
            </Link>
            <Link href="/about" className="create-campaign-btn">
              About
            </Link>
            <Link href="/create-campaign" className="create-campaign-btn">
              Create Campaign
            </Link>
            <Link href="/withdrawal" className="create-campaign-btn">
              Withdrawal
            </Link>
          </div>
          <WalletButton />
        </header> */}

        <Header />
        <div style={{ paddingTop: 80 }}>{children}</div>
      </body>
    </html>
  );
}
